#!/usr/bin/env python3
"""
Session Analyzer Module

Analyzes session logs generated by TransparentSessionLogger or PexpectSessionManager.
Extracts patterns, generates statistics, and suggests pexpect code.

Usage:
    python session_analyzer.py <log_file>
    python session_analyzer.py <log_file> --format pexpect
    python session_analyzer.py <log_file> --format summary
"""

import re
import json
import argparse
import sys
from pathlib import Path
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from collections import Counter, defaultdict
from enum import Enum

class EntryType(Enum):
    """Types of log entries."""
    INPUT = "INPUT"
    OUTPUT = "OUTPUT"
    ERROR = "ERROR"
    INFO = "INFO"
    PROMPT = "PROMPT"
    TIMEOUT = "TIMEOUT"
    CHECKPOINT = "CHECKPOINT"
    MARKER = "MARKER"
    RESUME_POINT = "RESUME_POINT"
    RESUME_POINT_DATA = "RESUME_POINT_DATA"


@dataclass
class LogEntry:
    """Represents a single parsed log entry."""
    timestamp: datetime
    entry_type: EntryType
    session_id: str
    content: str
    raw_line: str
    line_number: int

    @property
    def is_command(self) -> bool:
        """Check if this entry is a user command."""
        return self.entry_type == EntryType.INPUT and "\n" in self.content

    @property
    def clean_content(self) -> str:
        """Get content with escapes processed."""
        return (
            self.content
            .replace("\\n", "\n")
            .replace("\\r", "\r")
            .replace("\\t", "\t")
        )


@dataclass
class CommandSequence:
    """Represents a command and its output."""
    command: str
    input_entry: LogEntry
    output_entries: List[LogEntry] = field(default_factory=list)
    response_time_ms: float = 0.0
    prompt_detected: Optional[str] = None
    phase: Optional[str] = None
    checkpoint: Optional[str] = None

    @property
    def full_output(self) -> str:
        """Combine all output entries."""
        return "".join(e.clean_content for e in self.output_entries)


@dataclass
class PatternMatch:
    """Represents a detected pattern."""
    pattern_type: str
    pattern: str
    occurrences: int
    example: str
    confidence: float = 1.0


@dataclass
class SessionAnalysis:
    """Complete analysis results."""
    session_id: str
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    duration: timedelta = field(default_factory=lambda: timedelta(0))
    total_entries: int = 0
    command_count: int = 0
    commands: List[CommandSequence] = field(default_factory=list)
    patterns: List[PatternMatch] = field(default_factory=list)
    statistics: Dict[str, Any] = field(default_factory=dict)
    issues: List[Dict[str, Any]] = field(default_factory=list)
    suggestions: List[str] = field(default_factory=list)

class LogParser:
    """Parser for session log files."""

    # Log format: [YYYY-MM-DD HH:MM:SS.mmm] [TYPE] [SESSION_ID] content
    LOG_PATTERN = re.compile(
        r"\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\]\s+"  # timestamp
        r"\[(\w+)\]\s+"                                          # entry type
        r"\[([\w_]+)\]\s+"                                       # session id
        r"(.+)"                                                  # content
    )

    @classmethod
    def parse_file(cls, log_file: Path) -> List[LogEntry]:
        """
        Parse a log file into LogEntry objects.

        Args:
            log_file: Path to the log file

        Returns:
            List of parsed LogEntry objects

        Raises:
            FileNotFoundError: If log file doesn't exist
        """
        if not log_file.exists():
            raise FileNotFoundError(f"Log file not found: {log_file}")

        entries: List[LogEntry] = []

        with log_file.open("r", encoding="utf-8", errors="replace") as f:
            for line_num, line in enumerate(f, 1):
                line = line.rstrip("\n")
                if not line.strip():
                    continue

                entry = cls.parse_line(line, line_num)
                if entry:
                    entries.append(entry)

        return entries

    @classmethod
    def parse_line(cls, line: str, line_number: int) -> Optional[LogEntry]:
        """Parse a single log line."""
        match = cls.LOG_PATTERN.match(line)

        if not match:
            # Try to handle malformed lines gracefully
            return cls._parse_malformed_line(line, line_number)

        timestamp_str, entry_type_str, session_id, content = match.groups()

        try:
            timestamp = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S.%f")
        except ValueError:
            timestamp = datetime.now()

        # Parse entry type
        try:
            entry_type = EntryType(entry_type_str.upper())
        except ValueError:
            entry_type = EntryType.INFO

        # Clean up content (remove surrounding quotes if present)
        content = content.strip()
        if content.startswith("'") and content.endswith("'"):
            content = content[1:-1]
        elif content.startswith('"') and content.endswith('"'):
            content = content[1:-1]

        return LogEntry(
            timestamp=timestamp,
            entry_type=entry_type,
            session_id=session_id,
            content=content,
            raw_line=line,
            line_number=line_number,
        )

    @classmethod
    def _parse_malformed_line(cls, line: str, line_number: int) -> Optional[LogEntry]:
        """Attempt to parse malformed lines."""
        # Treat as continuation output if it doesn't look like a proper header
        if line.startswith(" ") or not line.startswith("["):
            return LogEntry(
                timestamp=datetime.now(),
                entry_type=EntryType.OUTPUT,
                session_id="unknown",
                content=line,
                raw_line=line,
                line_number=line_number,
            )
        return None

class PatternDetector:
    """Detects patterns in session logs."""

    # Common prompt patterns
    PROMPT_PATTERNS: Dict[str, str] = {
        "bash_basic": r"[\$#]\s*$",
        "bash_with_host": r"\[\w+@[\w\-]+:[^\]]+\][\$#]\s*$",
        "nixos": r"\[nixos@nixos:[^\]]+\][\$#]\s*$",
        "cisco": r"[\w\-]+[>#]\s*$",
        "cisco_config": r"[\w\-]+\((config[^\)]*)\)[#>]\s*$",
        "juniper": r"\w+@[\w\-]+[>#]\s*$",
        "root": r"#\s*$",
        "windows": r"[A-Z]:\\[^>]*>\s*$",
        "powershell": r"PS [A-Z]:\\[^>]*>\s*$",
    }

    # Common error patterns
    ERROR_PATTERNS: Dict[str, str] = {
        "command_not_found": r"command not found",
        "permission_denied": r"permission denied",
        "no_such_file": r"no such file or directory",
        "timeout": r"time(d)?\s*out",
        "connection_refused": r"connection refused",
        "authentication_failed": r"(authentication|login)\s*(failed|failure)",
    }

    @classmethod
    def detect_prompts(cls, entries: List[LogEntry]) -> List[PatternMatch]:
        """Detect prompt patterns in output."""
        patterns_found: List[PatternMatch] = []

        for name, pattern in cls.PROMPT_PATTERNS.items():
            matches = 0
            example = ""

            for entry in entries:
                if entry.entry_type == EntryType.OUTPUT:
                    content = entry.clean_content
                    if re.search(pattern, content, re.IGNORECASE | re.MULTILINE):
                        matches += 1
                        if not example:
                            example = cls._extract_prompt_example(content, pattern)

            if matches > 0:
                patterns_found.append(
                    PatternMatch(
                        pattern_type="prompt",
                        pattern=pattern,
                        occurrences=matches,
                        example=example,
                        confidence=min(1.0, matches / max(len(entries) * 0.1, 1)),
                    )
                )

        return sorted(patterns_found, key=lambda x: x.occurrences, reverse=True)

    @classmethod
    def detect_errors(cls, entries: List[LogEntry]) -> List[PatternMatch]:
        """Detect error patterns in output."""
        patterns_found: List[PatternMatch] = []

        for name, pattern in cls.ERROR_PATTERNS.items():
            matches = 0
            example = ""

            for entry in entries:
                if entry.entry_type in (EntryType.OUTPUT, EntryType.ERROR):
                    content = entry.clean_content
                    if re.search(pattern, content, re.IGNORECASE):
                        matches += 1
                        if not example:
                            example = content[:100]

            if matches > 0:
                patterns_found.append(
                    PatternMatch(
                        pattern_type="error",
                        pattern=pattern,
                        occurrences=matches,
                        example=example,
                        confidence=0.9,
                    )
                )

        return patterns_found

    @classmethod
    def detect_timing_issues(cls, entries: List[LogEntry]) -> List[Dict[str, Any]]:
        """Detect potential timing issues."""
        issues: List[Dict[str, Any]] = []
        last_input: Optional[LogEntry] = None

        for entry in entries:
            if entry.entry_type == EntryType.INPUT:
                last_input = entry
            elif entry.entry_type == EntryType.OUTPUT and last_input:
                gap = (entry.timestamp - last_input.timestamp).total_seconds()
                if gap > 10.0:
                    issues.append(
                        {
                            "type": "slow_response",
                            "after_command": last_input.clean_content[:50],
                            "delay_seconds": gap,
                            "timestamp": entry.timestamp.isoformat(),
                        }
                    )
                last_input = None

        return issues

    @classmethod
    def _extract_prompt_example(cls, content: str, pattern: str) -> str:
        """Extract an example of a prompt from content."""
        lines = content.split("\n")
        for line in reversed(lines):
            if re.search(pattern, line, re.IGNORECASE):
                return line.strip()[-50:]
        return content[-50:]

class CommandExtractor:
    """Extracts command sequences from log entries."""

    @classmethod
    def extract_commands(cls, entries: List[LogEntry]) -> List[CommandSequence]:
        """
        Extract command sequences from log entries.

        A command sequence consists of:
        - INPUT: The command entered
        - OUTPUT: The resulting output (until next INPUT, structural boundary, or end)

        Structural boundaries:
        - MARKER, CHECKPOINT, RESUME_POINT end the current command (if any)
          and set phase/checkpoint labels for subsequent commands.
        """
        commands: List[CommandSequence] = []
        current_command: Optional[CommandSequence] = None

        current_phase: Optional[str] = None
        current_checkpoint: Optional[str] = None

        def finalize_current():
            """Finish the current command, computing response time."""
            nonlocal current_command
            if not current_command:
                return
            if current_command.output_entries:
                first_output = current_command.output_entries[0].timestamp
                current_command.response_time_ms = (
                    (first_output - current_command.input_entry.timestamp)
                    .total_seconds() * 1000
                )
            commands.append(current_command)
            current_command = None

        for entry in entries:
            et = entry.entry_type

            if et == EntryType.INPUT:
                # New command: close previous one first
                finalize_current()

                cmd_text = entry.clean_content.strip()
                if cmd_text.endswith("\n"):
                    cmd_text = cmd_text[:-1]

                current_command = CommandSequence(
                    command=cmd_text,
                    input_entry=entry,
                    phase=current_phase,
                    checkpoint=current_checkpoint,
                )

            elif et in (EntryType.OUTPUT, EntryType.ERROR):
                if current_command:
                    current_command.output_entries.append(entry)
                    if et == EntryType.ERROR:
                        current_command.prompt_detected = "ERROR"

            elif et in (EntryType.MARKER, EntryType.CHECKPOINT, EntryType.RESUME_POINT):
                # Structural boundary: close any open command
                finalize_current()

                label = entry.clean_content.strip()

                if et == EntryType.MARKER:
                    current_phase = label or f"MARKER@{entry.line_number}"

                elif et == EntryType.CHECKPOINT:
                    current_checkpoint = label or f"CHECKPOINT@{entry.line_number}"

                elif et == EntryType.RESUME_POINT:
                    clean = label.strip("= ").strip()
                    current_checkpoint = clean or f"RESUME@{entry.line_number}"

            else:
                # INFO, PROMPT, TIMEOUT, RESUME_POINT_DATA, etc.
                continue

        # Don't forget the last command
        finalize_current()

        return commands

    @classmethod
    def categorize_commands(cls, commands: List[CommandSequence]) -> Dict[str, List[CommandSequence]]:
        """Categorize commands by type."""
        categories: Dict[str, List[CommandSequence]] = defaultdict(list)

        for cmd in commands:
            cmd_text = cmd.command.lower().strip()

            if cmd_text.startswith("ssh "):
                categories["ssh"].append(cmd)
            elif cmd_text.startswith("sudo "):
                categories["sudo"].append(cmd)
            elif cmd_text.startswith("cd "):
                categories["navigation"].append(cmd)
            elif cmd_text.startswith("ls") or cmd_text.startswith("dir"):
                categories["listing"].append(cmd)
            elif cmd_text.startswith("cat ") or cmd_text.startswith("less "):
                categories["viewing"].append(cmd)
            elif cmd_text.startswith("python") or cmd_text.startswith("python3"):
                categories["python"].append(cmd)
            elif any(x in cmd_text for x in ["configure", "config", "setup", "install"]):
                categories["configuration"].append(cmd)
            else:
                categories["other"].append(cmd)

        return dict(categories)

class StatisticsGenerator:
    """Generates statistics from session data."""

    @classmethod
    def generate(cls, entries: List[LogEntry], commands: List[CommandSequence]) -> Dict[str, Any]:
        """Generate comprehensive statistics."""
        if not entries:
            return {}

        # Time range
        timestamps = [e.timestamp for e in entries if e.timestamp]
        start_time = min(timestamps) if timestamps else None
        end_time = max(timestamps) if timestamps else None
        duration = (end_time - start_time) if start_time and end_time else timedelta(0)

        # Entry counts
        type_counts = Counter(e.entry_type.name for e in entries)

        # Command statistics
        cmd_lengths = [len(cmd.command) for cmd in commands]
        response_times = [cmd.response_time_ms for cmd in commands if cmd.response_time_ms > 0]

        # Output sizes
        output_sizes: List[int] = []
        for cmd in commands:
            total = sum(len(e.content) for e in cmd.output_entries)
            output_sizes.append(total)

        # Unique commands
        unique_commands = set(cmd.command for cmd in commands)

        # Command frequency
        command_freq = Counter(cmd.command for cmd in commands)

        # Phase / checkpoint breakdown
        phase_counts = Counter((cmd.phase or "(no phase)") for cmd in commands)
        checkpoint_counts = Counter((cmd.checkpoint or "(no checkpoint)") for cmd in commands)

        phases_info = {
            "by_phase": [
                {"name": name, "command_count": count}
                for name, count in phase_counts.items()
                if name != "(no phase)"
            ],
            "by_checkpoint": [
                {"name": name, "command_count": count}
                for name, count in checkpoint_counts.items()
                if name != "(no checkpoint)"
            ],
        }

        stats: Dict[str, Any] = {
            "time_range": {
                "start": start_time.isoformat() if start_time else None,
                "end": end_time.isoformat() if end_time else None,
                "duration_seconds": duration.total_seconds(),
                "duration_formatted": cls._format_duration(duration),
            },
            "entry_counts": dict(type_counts),
            "commands": {
                "total": len(commands),
                "unique": len(unique_commands),
                "avg_length": sum(cmd_lengths) / len(cmd_lengths) if cmd_lengths else 0,
                "max_length": max(cmd_lengths) if cmd_lengths else 0,
                "avg_response_ms": sum(response_times) / len(response_times) if response_times else 0,
                "max_response_ms": max(response_times) if response_times else 0,
                "min_response_ms": min(response_times) if response_times else 0,
            },
            "output": {
                "total_bytes": sum(output_sizes),
                "avg_per_command": sum(output_sizes) / len(output_sizes) if output_sizes else 0,
                "commands_with_output": sum(1 for s in output_sizes if s > 0),
            },
            "most_common_commands": command_freq.most_common(10),
            "timing": {
                "fastest_response_ms": min(response_times) if response_times else 0,
                "slowest_response_ms": max(response_times) if response_times else 0,
            },
            "phases": phases_info,
        }

        return stats

    @staticmethod
    def _format_duration(delta: timedelta) -> str:
        """Format timedelta as human-readable string."""
        total_seconds = int(delta.total_seconds())
        hours = total_seconds // 3600
        minutes = (total_seconds % 3600) // 60
        seconds = total_seconds % 60

        parts: List[str] = []
        if hours > 0:
            parts.append(f"{hours}h")
        if minutes > 0:
            parts.append(f"{minutes}m")
        if seconds > 0 or not parts:
            parts.append(f"{seconds}s")

        return " ".join(parts)

class PexpectCodeGenerator:
    """Generates pexpect code from analyzed sessions."""

    @classmethod
    def generate_script(
        cls,
        commands: List[CommandSequence],
        patterns: List[PatternMatch],
        session_id: str,
        scope: Optional[Dict[str, str]] = None,
    ) -> str:
        """Generate a complete pexpect script from commands."""

        # Extract prompts
        prompt_patterns = [p for p in patterns if p.pattern_type == "prompt"]
        main_prompt = prompt_patterns[0].pattern if prompt_patterns else r"[\$#]\s*$"

        scope_lines: List[str] = []
        if scope:
            if scope.get("phase"):
                scope_lines.append(f"Filtered by phase: {scope['phase']}")
            if scope.get("checkpoint"):
                scope_lines.append(f"Filtered by checkpoint: {scope['checkpoint']}")

        # Build script
        lines = [
            "#!/usr/bin/env python3",
            '"""',
            f"Auto-generated pexpect script from session: {session_id}",
            f"Generated: {datetime.now().isoformat()}",
            "",
            "This script was created by analyzing your interactive session.",
            "Review and modify as needed before using in production.",
        ]

        if scope_lines:
            lines.append("")
            lines.append("Applied filters:")
            for line in scope_lines:
                lines.append(f"- {line}")

        lines.extend(
            [
                '"""',
                "",
                "import pexpect",
                "import sys",
                "import time",
                "",
                "# Configuration",
                "DEFAULT_TIMEOUT = 30",
                f"PROMPT_PATTERN = r'{main_prompt}'",
                "",
                "def main():",
                '    """Execute the automation workflow."""',
                "    child = None",
                "",
                "    try:",
            ]
        )

        # Detect if SSH is used
        ssh_commands = [cmd for cmd in commands if cmd.command.startswith("ssh ")]

        if ssh_commands:
            first_ssh = ssh_commands[0]
            lines.extend(
                [
                    "        # Establish SSH connection",
                    "        child = pexpect.spawn(",
                    f"            {repr(first_ssh.command)},",
                    "            encoding='utf-8',",
                    "            timeout=DEFAULT_TIMEOUT",
                    "        )",
                    "        child.logfile_read = sys.stdout",
                    "",
                    "        # Wait for password prompt",
                    "        child.expect(r'(?i)password:', timeout=10)",
                    "        child.sendline('YOUR_PASSWORD_HERE')  # TODO: Secure this!",
                    "",
                    "        # Wait for shell prompt",
                    "        child.expect(PROMPT_PATTERN)",
                    "        print('[✓] SSH connection established')",
                    "",
                ]
            )

            # Skip the SSH command in the loop
            remaining_commands = [c for c in commands if not c.command.startswith("ssh ")]
        else:
            # Start a local shell
            lines.extend(
                [
                    "        # Start local shell",
                    "        child = pexpect.spawn(",
                    "            '/bin/bash',",
                    "            encoding='utf-8',",
                    "            timeout=DEFAULT_TIMEOUT",
                    "        )",
                    "        child.logfile_read = sys.stdout",
                    "        child.expect(PROMPT_PATTERN)",
                    "",
                ]
            )
            remaining_commands = commands

        # Generate code for each command
        for idx, cmd in enumerate(remaining_commands[:20], 1):  # Limit to first 20 commands
            if not cmd.command.strip():
                continue

            header = f"        # Command {idx}: {cmd.command[:50]}"
            if cmd.phase or cmd.checkpoint:
                parts = []
                if cmd.phase:
                    parts.append(f"phase={cmd.phase}")
                if cmd.checkpoint:
                    parts.append(f"checkpoint={cmd.checkpoint}")
                header += "  [" + ", ".join(parts) + "]"
            lines.append(header)

            if cmd.command.startswith("sudo "):
                lines.extend(
                    [
                        f"        child.sendline({repr(cmd.command)})",
                        "",
                        "        # Handle potential sudo password prompt",
                        "        idx = child.expect([PROMPT_PATTERN, r'(?i)\\[sudo\\] password'], timeout=10)",
                        "        if idx == 1:  # Password prompt",
                        "            child.sendline('YOUR_SUDO_PASSWORD')  # TODO: Secure this!",
                        "            child.expect(PROMPT_PATTERN)",
                        "",
                    ]
                )
            else:
                timeout = (
                    max(30, int(cmd.response_time_ms / 1000) + 5)
                    if cmd.response_time_ms
                    else 30
                )
                lines.extend(
                    [
                        f"        child.sendline({repr(cmd.command)})",
                        f"        child.expect(PROMPT_PATTERN, timeout={timeout})",
                        "",
                    ]
                )

            if cmd.prompt_detected == "ERROR":
                lines.extend(
                    [
                        "        # Warning: This command may have produced errors in the original session",
                        "        # TODO: Add error handling here",
                        "",
                    ]
                )

        # Footer
        lines.extend(
            [
                "        print('[✓] All commands completed successfully')",
                "",
                "    except pexpect.TIMEOUT:",
                "        print('[✗] Timeout waiting for response')",
                "        if child:",
                "            print(f'Buffer: {child.before}')",
                "        sys.exit(1)",
                "",
                "    except pexpect.EOF:",
                "        print('[✗] Connection closed unexpectedly')",
                "        sys.exit(1)",
                "",
                "    except KeyboardInterrupt:",
                "        print('\\n[!] Interrupted by user')",
                "        sys.exit(130)",
                "",
                "    except Exception as e:",
                "        print(f'[✗] Error: {e}')",
                "        import traceback",
                "        traceback.print_exc()",
                "        sys.exit(1)",
                "",
                "    finally:",
                "        if child:",
                "            child.close()",
                "",
                "",
                "if __name__ == '__main__':",
                "    main()",
                "",
            ]
        )

        return "\n".join(lines)

    @classmethod
    def generate_patterns_module(cls, patterns: List[PatternMatch]) -> str:
        """Generate a Python module with detected patterns."""
        lines: List[str] = [
            '"""',
            "Detected patterns from session analysis.",
            "Import this module to use the patterns in your scripts.",
            '"""',
            "",
            "import re",
            "",
            "# Detected Prompt Patterns",
        ]

        prompt_patterns = [p for p in patterns if p.pattern_type == "prompt"]
        for idx, pattern in enumerate(prompt_patterns, 1):
            lines.append(f"PROMPT_{idx} = r'{pattern.pattern}'")
            lines.append(f"# Example: {pattern.example}")
            lines.append(f"# Found {pattern.occurrences} times")
            lines.append("")

        lines.append("# All prompt patterns")
        lines.append("ALL_PROMPTS = [")
        for idx in range(1, len(prompt_patterns) + 1):
            lines.append(f"    PROMPT_{idx},")
        lines.append("]")
        lines.append("")

        # Error patterns
        error_patterns = [p for p in patterns if p.pattern_type == "error"]
        if error_patterns:
            lines.append("# Detected Error Patterns")
            for idx, pattern in enumerate(error_patterns, 1):
                lines.append(f"ERROR_{idx} = r'{pattern.pattern}'")
                lines.append(f"# Example: {pattern.example[:50]}")
                lines.append("")

        return "\n".join(lines)

class SessionAnalyzer:
    """Main analyzer class coordinating all analysis components."""

    def __init__(self, log_file: Path):
        """Initialize analyzer with log file."""
        self.log_file = log_file
        self.entries: List[LogEntry] = []
        self.commands: List[CommandSequence] = []
        self.analysis: Optional[SessionAnalysis] = None

    def analyze(self) -> SessionAnalysis:
        """Perform complete analysis of the session log."""
        # Parse log file
        print(f"📖 Parsing log file: {self.log_file}")
        self.entries = LogParser.parse_file(self.log_file)
        print(f"   Found {len(self.entries)} log entries")

        if not self.entries:
            print("⚠️  No entries found in log file")
            return SessionAnalysis(session_id="empty")

        # Extract commands
        print("🔍 Extracting command sequences...")
        self.commands = CommandExtractor.extract_commands(self.entries)
        print(f"   Found {len(self.commands)} commands")

        # Detect patterns
        print("🎯 Detecting patterns...")
        prompt_patterns = PatternDetector.detect_prompts(self.entries)
        error_patterns = PatternDetector.detect_errors(self.entries)
        all_patterns = prompt_patterns + error_patterns
        print(f"   Detected {len(all_patterns)} patterns")

        # Detect timing issues
        print("⏱️  Analyzing timing...")
        timing_issues = PatternDetector.detect_timing_issues(self.entries)

        # Generate statistics
        print("📊 Generating statistics...")
        statistics = StatisticsGenerator.generate(self.entries, self.commands)

        # Create analysis result
        session_id = self.entries[0].session_id if self.entries else "unknown"

        # Generate suggestions
        suggestions = self._generate_suggestions(
            prompt_patterns,
            error_patterns,
            timing_issues,
            statistics,
        )

        self.analysis = SessionAnalysis(
            session_id=session_id,
            start_time=datetime.fromisoformat(statistics["time_range"]["start"])
            if statistics.get("time_range", {}).get("start")
            else None,
            end_time=datetime.fromisoformat(statistics["time_range"]["end"])
            if statistics.get("time_range", {}).get("end")
            else None,
            duration=timedelta(
                seconds=statistics.get("time_range", {}).get("duration_seconds", 0)
            ),
            total_entries=len(self.entries),
            command_count=len(self.commands),
            commands=self.commands,
            patterns=all_patterns,
            statistics=statistics,
            issues=timing_issues,
            suggestions=suggestions,
        )

        print("✅ Analysis complete\n")
        return self.analysis

    def _generate_suggestions(
        self,
        prompt_patterns: List[PatternMatch],
        error_patterns: List[PatternMatch],
        timing_issues: List[Dict[str, Any]],
        statistics: Dict[str, Any],
    ) -> List[str]:
        """Generate helpful suggestions based on analysis."""
        suggestions: List[str] = []

        # Prompt suggestions
        if len(prompt_patterns) > 1:
            suggestions.append(
                f"Multiple prompt patterns detected ({len(prompt_patterns)}). "
                f"Consider using the most common pattern: {prompt_patterns[0].pattern}"
            )
        elif len(prompt_patterns) == 1:
            suggestions.append(
                f"Consistent prompt detected: {prompt_patterns[0].example}. "
                f"Use pattern: r'{prompt_patterns[0].pattern}'"
            )
        else:
            suggestions.append(
                "No clear prompt pattern detected. "
                "Use a flexible pattern like r'[\\$#>]\\s*$'"
            )

        # Error handling suggestions
        if error_patterns:
            error_types = ", ".join(
                sorted({p.pattern.split()[0] for p in error_patterns[:3]})
            )
            suggestions.append(
                f"Errors detected: {error_types}. "
                f"Add error handling to your pexpect script."
            )

        # Timing suggestions
        if timing_issues:
            slowest = max(timing_issues, key=lambda x: x["delay_seconds"])
            suggestions.append(
                f"Slow responses detected (up to {slowest['delay_seconds']:.1f}s). "
                f"Consider increasing timeout values."
            )

        # Command repetition
        cmd_stats = statistics.get("commands", {})
        if cmd_stats.get("total", 0) > cmd_stats.get("unique", 1):
            repeat_ratio = cmd_stats["total"] / max(cmd_stats["unique"], 1)
            if repeat_ratio > 2:
                suggestions.append(
                    f"Commands are repeated {repeat_ratio:.1f}x on average. "
                    f"Consider using loops in your pexpect script."
                )

        # Response time variance
        avg_response = cmd_stats.get("avg_response_ms", 0)
        max_response = cmd_stats.get("max_response_ms", 0)
        if max_response > avg_response * 5 and avg_response > 0:
            suggestions.append(
                f"Response times vary significantly ({avg_response:.0f}ms avg, {max_response:.0f}ms max). "
                f"Use per-command timeouts instead of a single global timeout."
            )

        return suggestions

class ReportGenerator:
    """Generates formatted reports from analysis."""

    @classmethod
    def generate_summary(cls, analysis: SessionAnalysis) -> str:
        """Generate a human-readable summary report."""
        lines: List[str] = [
            "=" * 70,
            "SESSION ANALYSIS SUMMARY",
            "=" * 70,
            "",
            f"Session ID: {analysis.session_id}",
            f"Start Time: {analysis.start_time.strftime('%Y-%m-%d %H:%M:%S') if analysis.start_time else 'Unknown'}",
            f"Duration: {analysis.statistics.get('time_range', {}).get('duration_formatted', 'N/A')}",
            f"Total Entries: {analysis.total_entries}",
            "",
            "-" * 70,
            "COMMANDS",
            "-" * 70,
            f"Total Commands: {analysis.command_count}",
            f"Unique Commands: {analysis.statistics.get('commands', {}).get('unique', 0)}",
            f"Average Response Time: {analysis.statistics.get('commands', {}).get('avg_response_ms', 0):.0f}ms",
            "",
        ]

        # Phase / checkpoint overview
        phase_stats = analysis.statistics.get("phases", {}).get("by_phase", [])
        checkpoint_stats = analysis.statistics.get("phases", {}).get("by_checkpoint", [])

        if phase_stats:
            lines.append("Phases:")
            for ph in phase_stats[:10]:
                lines.append(f"  - {ph['name']}: {ph['command_count']} commands")
            lines.append("")

        if checkpoint_stats:
            lines.append("Checkpoints:")
            for cp in checkpoint_stats[:10]:
                lines.append(f"  - {cp['name']}: {cp['command_count']} commands")
            lines.append("")

        # Most common commands
        most_common = analysis.statistics.get("most_common_commands", [])
        if most_common:
            lines.append("Most Common Commands:")
            for cmd, count in most_common[:5]:
                lines.append(f"  {count:3d}x  {cmd[:60]}")
            lines.append("")

        # Patterns
        lines.extend(
            [
                "-" * 70,
                "DETECTED PATTERNS",
                "-" * 70,
            ]
        )

        prompt_patterns = [p for p in analysis.patterns if p.pattern_type == "prompt"]
        if prompt_patterns:
            lines.append("Prompt Patterns:")
            for pattern in prompt_patterns[:3]:
                lines.append(f"  Pattern: {pattern.pattern}")
                lines.append(f"  Example: {pattern.example}")
                lines.append(f"  Found: {pattern.occurrences} times")
                lines.append("")

        error_patterns = [p for p in analysis.patterns if p.pattern_type == "error"]
        if error_patterns:
            lines.append("Error Patterns:")
            for pattern in error_patterns[:3]:
                lines.append(f"  Pattern: {pattern.pattern}")
                lines.append(f"  Found: {pattern.occurrences} times")
            lines.append("")

        # Issues
        if analysis.issues:
            lines.extend(
                [
                    "-" * 70,
                    "TIMING ISSUES",
                    "-" * 70,
                ]
            )
            for issue in analysis.issues[:5]:
                lines.append(f"  Slow response after: {issue['after_command']}")
                lines.append(f"  Delay: {issue['delay_seconds']:.1f}s")
                lines.append("")

        # Suggestions
        if analysis.suggestions:
            lines.extend(
                [
                    "-" * 70,
                    "SUGGESTIONS",
                    "-" * 70,
                ]
            )
            for idx, suggestion in enumerate(analysis.suggestions, 1):
                lines.append(f"{idx}. {suggestion}")
            lines.append("")

        lines.append("=" * 70)

        return "\n".join(lines)

    @classmethod
    def generate_json(cls, analysis: SessionAnalysis) -> str:
        """Generate JSON report."""
        data = {
            "session_id": analysis.session_id,
            "start_time": analysis.start_time.isoformat() if analysis.start_time else None,
            "end_time": analysis.end_time.isoformat() if analysis.end_time else None,
            "duration_seconds": analysis.duration.total_seconds(),
            "total_entries": analysis.total_entries,
            "command_count": analysis.command_count,
            "patterns": [
                {
                    "type": p.pattern_type,
                    "pattern": p.pattern,
                    "occurrences": p.occurrences,
                    "example": p.example,
                    "confidence": p.confidence,
                }
                for p in analysis.patterns
            ],
            "statistics": analysis.statistics,
            "issues": analysis.issues,
            "suggestions": analysis.suggestions,
        }

        return json.dumps(data, indent=2, default=str)

    @classmethod
    def generate_markdown(cls, analysis: SessionAnalysis) -> str:
        """Generate Markdown report."""
        lines: List[str] = [
            f"# Session Analysis: {analysis.session_id}",
            "",
            "## Overview",
            "",
            f"- **Start Time:** {analysis.start_time.strftime('%Y-%m-%d %H:%M:%S') if analysis.start_time else 'Unknown'}",
            f"- **Duration:** {analysis.statistics.get('time_range', {}).get('duration_formatted', 'N/A')}",
            f"- **Commands Executed:** {analysis.command_count}",
            f"- **Total Log Entries:** {analysis.total_entries}",
            "",
            "## Command Statistics",
            "",
            f"- Total commands: **{analysis.command_count}**",
            f"- Unique commands: **{analysis.statistics.get('commands', {}).get('unique', 0)}**",
            f"- Average response time: **{analysis.statistics.get('commands', {}).get('avg_response_ms', 0):.0f}ms**",
            f"- Fastest response: **{analysis.statistics.get('commands', {}).get('min_response_ms', 0):.0f}ms**",
            f"- Slowest response: **{analysis.statistics.get('commands', {}).get('max_response_ms', 0):.0f}ms**",
            "",
        ]

        # Phases and checkpoints
        phase_stats = analysis.statistics.get("phases", {}).get("by_phase", [])
        checkpoint_stats = analysis.statistics.get("phases", {}).get("by_checkpoint", [])

        if phase_stats or checkpoint_stats:
            lines.extend(
                [
                    "## Phases and checkpoints",
                    "",
                ]
            )

        if phase_stats:
            lines.extend(
                [
                    "### Phases",
                    "",
                    "| Phase | Commands |",
                    "|-------|----------|",
                ]
            )
            for ph in phase_stats:
                lines.append(f"| `{ph['name']}` | {ph['command_count']} |")
            lines.append("")

        if checkpoint_stats:
            lines.extend(
                [
                    "### Checkpoints",
                    "",
                    "| Checkpoint | Commands |",
                    "|------------|----------|",
                ]
            )
            for cp in checkpoint_stats:
                lines.append(f"| `{cp['name']}` | {cp['command_count']} |")
            lines.append("")

        # Most common commands
        most_common = analysis.statistics.get("most_common_commands", [])
        if most_common:
            lines.extend(
                [
                    "### Most Common Commands",
                    "",
                    "| Count | Command |",
                    "|-------|---------|",
                ]
            )
            for cmd, count in most_common[:10]:
                lines.append(f"| {count} | `{cmd[:60]}` |")
            lines.append("")

        # Patterns
        prompt_patterns = [p for p in analysis.patterns if p.pattern_type == "prompt"]
        if prompt_patterns:
            lines.extend(
                [
                    "## Detected Prompt Patterns",
                    "",
                ]
            )
            for pattern in prompt_patterns:
                lines.extend(
                    [
                        f"### Pattern: `{pattern.pattern}`",
                        "",
                        f"- **Example:** `{pattern.example}`",
                        f"- **Occurrences:** {pattern.occurrences}",
                        f"- **Confidence:** {pattern.confidence:.2f}",
                        "",
                    ]
                )

        # Errors
        error_patterns = [p for p in analysis.patterns if p.pattern_type == "error"]
        if error_patterns:
            lines.extend(
                [
                    "## Error Patterns",
                    "",
                ]
            )
            for pattern in error_patterns:
                lines.extend(
                    [
                        f"- **Pattern:** `{pattern.pattern}`",
                        f"  - Found {pattern.occurrences} times",
                        f"  - Example: `{pattern.example[:80]}`",
                        "",
                    ]
                )

        # Suggestions
        if analysis.suggestions:
            lines.extend(
                [
                    "## Recommendations",
                    "",
                ]
            )
            for suggestion in analysis.suggestions:
                lines.append(f"- {suggestion}")
            lines.append("")

        return "\n".join(lines)

def _filter_commands_by_scope(
    commands: List[CommandSequence],
    phase: Optional[str] = None,
    checkpoint: Optional[str] = None,
) -> List[CommandSequence]:
    """
    Filter commands by phase and/or checkpoint.

    - If phase is provided, only commands with CommandSequence.phase matching (case-insensitive) are kept.
    - If checkpoint is provided, only commands with CommandSequence.checkpoint matching are kept.
    - If both are provided, both conditions must match.
    """
    if not phase and not checkpoint:
        return commands

    phase_lower = phase.lower() if phase else None
    checkpoint_lower = checkpoint.lower() if checkpoint else None

    filtered: List[CommandSequence] = []
    for cmd in commands:
        if phase_lower:
            if not cmd.phase or cmd.phase.lower() != phase_lower:
                continue
        if checkpoint_lower:
            if not cmd.checkpoint or cmd.checkpoint.lower() != checkpoint_lower:
                continue
        filtered.append(cmd)

    return filtered


def main():
    """Main entry point for the analyzer."""
    parser = argparse.ArgumentParser(
        description="Analyze pexpect session logs and generate automation code",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Analyze a session log
  python session_analyzer.py session.log

  # Generate pexpect script
  python session_analyzer.py session.log --format pexpect

  # Generate JSON report
  python session_analyzer.py session.log --format json > report.json

  # Generate markdown report
  python session_analyzer.py session.log --format markdown > report.md

  # Generate pexpect script for a specific phase
  python session_analyzer.py session.log --format pexpect --phase "MIGRATION PHASE"

  # Generate pexpect script from a specific checkpoint
  python session_analyzer.py session.log --format pexpect --checkpoint "after_login"
        """,
    )

    parser.add_argument(
        "log_file",
        type=Path,
        help="Path to the session log file",
    )

    parser.add_argument(
        "--format",
        choices=["summary", "json", "markdown", "pexpect", "patterns"],
        default="summary",
        help="Output format (default: summary)",
    )

    parser.add_argument(
        "--output",
        type=Path,
        help="Output file (default: stdout)",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Verbose output during analysis",
    )

    parser.add_argument(
        "--phase",
        help="Only include commands from this phase when generating pexpect script",
    )

    parser.add_argument(
        "--checkpoint",
        help="Only include commands from this checkpoint when generating pexpect script",
    )

    args = parser.parse_args()

    # Check if log file exists
    if not args.log_file.exists():
        print(f"❌ Error: Log file not found: {args.log_file}", file=sys.stderr)
        sys.exit(1)

    try:
        # Analyze the session
        analyzer = SessionAnalyzer(args.log_file)
        analysis = analyzer.analyze()

        # Generate output
        if args.format == "summary":
            output = ReportGenerator.generate_summary(analysis)
        elif args.format == "json":
            output = ReportGenerator.generate_json(analysis)
        elif args.format == "markdown":
            output = ReportGenerator.generate_markdown(analysis)
        elif args.format == "pexpect":
            scope = {
                k: v
                for k, v in {
                    "phase": args.phase,
                    "checkpoint": args.checkpoint,
                }.items()
                if v
            }

            commands = analysis.commands
            if scope:
                commands = _filter_commands_by_scope(
                    commands,
                    phase=scope.get("phase"),
                    checkpoint=scope.get("checkpoint"),
                )

            output = PexpectCodeGenerator.generate_script(
                commands,
                analysis.patterns,
                analysis.session_id,
                scope if scope else None,
            )
        elif args.format == "patterns":
            output = PexpectCodeGenerator.generate_patterns_module(analysis.patterns)
        else:
            output = ReportGenerator.generate_summary(analysis)

        # Write output
        if args.output:
            with args.output.open("w", encoding="utf-8") as f:
                f.write(output)
            print(f"✅ Output written to: {args.output}")
        else:
            print(output)

    except Exception as e:
        print(f"❌ Error during analysis: {e}", file=sys.stderr)
        if args.verbose:
            import traceback

            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
